### ISSUE TITLE
Drive Beacon v0.4 API specification through GA4GH Product Approval process

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/specification#137]
- [x] Fix remaining v0.4 API [bugs](https://github.com/ga4gh-beacon/specification/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Atheme%3AGA4GH-1.0+label%3Atype%3Abug)
- [x] Point to official Beacon repository in references #140 
- [ ]  [Create Beacon](https://github.com/ga4gh-beacon/beacon-elixir/issues/4) [v0.4.1](https://github.com/ga4gh-beacon/specification/milestone/8) Release with bug fixes
- [ ] Create [GA4GH Beacon 1.0 Specification document](https://github.com/ga4gh-beacon/specification/blob/develop/beacon.md) #179
- [ ] Complete [GA4GH Product Approval Process](https://docs.google.com/document/d/1UUJSnsPw32W5r1jaJ0vI11X0LLLygpAC9TNosjSge_w/edit#heading=h.tyqycskyykwh)
  - [ ] Complete [Data Security Preliminary Risk Assessment](https://docs.google.com/document/d/1DJ67JP7Ue2W2DJyDQdN2fx_dwc6yvUtu2U5GIBn5ek0/edit?ts=5ab0ce61)

**Comment by sdelatorrep** [comment]
Before releasing v0.4.1 we must also solve #139 and #140, which are not bugs.

**Comment by mbaudis** [comment]
Not mine.

(One has to have been at the Barcelona meeting to understand this unnecessary comment.)

**Comment by garysaunders** [comment]
Closed. Superseded by driving to 0.4.1
